version: '3.8'

services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql-1
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'  # If you want to change the port externally, you can modify this.
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'   # This will pick up the password from the .env file
            MYSQL_ROOT_HOST: '%'                    # This allows access from any host
            MYSQL_DATABASE: '${DB_DATABASE}'        # This will create the bookdb database as per the .env
            MYSQL_USER: '${DB_USERNAME}'            # This will pick up the username from the .env file
            MYSQL_PASSWORD: '${DB_PASSWORD}'        # This will pick up the password from the .env file
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql-1            # Use the MySQL service name from Docker
            PMA_PORT: 3306             # Use the port for MySQL
            MYSQL_ROOT_PASSWORD: root  # Use the root password from the .env file
        ports:
            - "8080:80"                # Access phpMyAdmin via localhost:8080
        networks:
            - sail


networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local